# Generated by Django 6.0.1 on 2026-02-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rushabh_infotech', '0002_alter_service_options_remove_contactmessage_subject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='service_interest',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
