# Generated by Django 6.0.1 on 2026-02-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rushabh_infotech', '0003_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('Unread', 'Unread'), ('Replied', 'Replied')], default='Unread', max_length=20),
        ),
    ]
