# Generated by Django 6.0.1 on 2026-02-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rushabh_infotech', '0004_alter_contactmessage_options_contactmessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='service_interest',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
